version: "3.8"
services:
  php:
    image: composer:2.4.1
#    user: multichain_client
    volumes:
      - ./:/app
    networks:
      - multichain_client
    entrypoint: tail -f /dev/null

  multichain:
    image: kunstmaan/master-multichain:latest
    networks:
      - multichain_client
    entrypoint: tail -f /dev/null

networks:
  multichain_client:
    driver: bridge